filebeat.inputs:
- type: container
  paths:
    - "/var/lib/docker/containers/*/*.log"
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
        process_array: false

output.elasticsearch:
  hosts: ["elasticsearch-logs:9200"]
  indices:
    - index: "docker-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false