name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wemake-python-styleguide
          pip install -r auth-service/tests/functional/requirements.txt
          pip install -r kafka-clickhouse-etl/requirements.txt
          pip install -r theater-service/tests/functional/requirements.txt
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Run tests auth-service
        run: |
          pytest auth-service/tests/functional
      - name: Run tests kafka-clickhouse-etl
        run: |
          pytest kafka-clickhouse-etl/tests/
      - name: Run tests theater-service
        run: |
          pytest theater-service/tests/functional
